apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameoflife
  labels:
    app: game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game
        image: bds1959/gameoflife:latest
        ports:
        - containerPort: 8080

